### ISSUE TITLE
[Xamarin.iOS] Error on method call ClearCookiesAsync()

### ISSUE THREAD

**Issue by stoff99** [devsmadeofsteel/Plugin.HybridWebView#4]
Hello @candidodmv ,

Sorry for spamming your Git repo but we found a bug when we call the method ClearCookiesAsync() on iOS.
![Screenshot_31_01_20__13_37](https://user-images.githubusercontent.com/892820/73540029-18e47b00-442f-11ea-9abe-604f0c7e41c4.png)

Xamarin Version: 4.3.0.991211
iOS: 13.1.3

Greetings
Stefan

**Comment by stoff99** [comment]
We currently found out that the same appears when you call the method GetAllCookiesAsync()

![Screenshot_31_01_20__14_01](https://user-images.githubusercontent.com/892820/73541288-5696d300-4432-11ea-80d9-24abddb2bdc3.png)

**Comment by candidodmv** [comment]
Hello @stoff99 , I'm looking in the source code, and i suppouse that what is causing this exceptions in both methods above, is due the tried of parse the `Element.Source` URL:

https://github.com/devsmadeofsteel/Plugin.HybridWebView/blob/f0d2915dea8d1d0befb4a13b1836b2ff6dc5d34d/HybridWebView/iOS/HybridWebViewRenderer.cs#L143

I'm considering instead of use `Uri.Parse`, use `Uri.TryCreate`, but I don't guarantee if is the best choice, could you help me to decide this?

**Comment by stoff99** [comment]
Hi @candidodmv ,
yes i think that makes sense.
After the parse check if the url is null.

**Comment by candidodmv** [comment]
@stoff99 I've pushed the new alpha release with this and #2 issue right now on a version [1.0.0.2-alpha](https://www.nuget.org/packages/Plugin.HybridWebView/1.0.0.2-alpha)

**Comment by stoff99** [comment]
Hello @candidodmv ,

this is fixed now. I don't get any exception with the 1.0.0.2 anymore.
Thx a lot

**Comment by candidodmv** [comment]
That's great @stoff99

**Comment by TechnikKTK** [comment]
Hello. I am using your solution, but I have an error. When calling the InjectJavaScriptAsync method, namely the result of calling callBack. There is an error describing the csharp function in the readme() on JS. because your code requires Base64 encoding and does not skip simple commands like eventObj.Sender.injectjavascript("csharp('Testing');"); because there is also deserialization going on. I corrected my hybrid, but somewhere in HandleScriptReceived there is an Exception null reference. I don't understand where.
